GET https://fullstackopencourse-part3-nd.fly.dev/api/persons

###
POST https://fullstackopencourse-part3-nd.fly.dev/api/persons
Content-Type: application/json

{
    "name": "John Bob", 
    "number": "39-23-6423122"
}